// Generated by https://quicktype.io

export interface Organization {
  contactEmail?: string;
  contactPhoneNumber?: string;
  organizationCode?: string;
  organizationId?: number;
  organizationName: string;
  organizationTypeId: string;
  percentageRetention?: number;
  physicalAddress: string;
  retention: boolean;
}
