// Generated by https://quicktype.io

import { Organization } from './organization.model';

export interface RevenueHeadRequest {
  amount: number;
  organisationId: number;
  percentageOfRetention: number;
  retaining: boolean;
  serviceCategoryCode: string;
  serviceName: string;
}

// Generated by https://quicktype.io

export interface RevenueHead {
  amount: number;
  organisationId: Organization;
  percentageOfRetention: number;
  retaining: boolean;
  serviceCategory: ServiceCategory;
  serviceId: number;
  serviceName: string;
}

export interface ServiceCategory {
  categoryDescription: string;
  categoryName: string;
  serviceCategoryCode: string;
  urlSlug: string;
}
